### ISSUE TITLE
Background not displaying correctly!?

### ISSUE THREAD

**Issue by mjmajadly** [WebAhead7/fly-webahead#14]
the background in the readme file not the same as the one on the site
![Capture](https://user-images.githubusercontent.com/43019810/98228258-0587b280-1f61-11eb-993c-e0aed13b170f.PNG)
![tenor](https://user-images.githubusercontent.com/43019810/98228334-1fc19080-1f61-11eb-9b1d-09b6d0fe7f49.gif)

**Comment by OmklthomAmara** [comment]
That's a feature not a bug.
